# IMPORTANT NOTE!: TO UPDATE THIS FILE TO THE LATEST VERSION:
# 1) MAKE A BACKUP AND DELETE THIS FILE.
# 2) START THE PLUGIN TO GENERATE THE NEW FILE.
# 3) RESTORE SETTINGS ACCORDING TO THE BACKUP FILE.
# 4) RELOAD PLUGIN AND THAT'S IT

# When the game starts everyone will be teleported in a random square radius
#   between 0 and teleportMaxDistance blocks from 0,0. (no more than 1.000.000 blocks)
teleportMaxDistance: 1000000

# Decide whether to teleport players:
#   - everyone together (ALL),
#   - everyone apart (ALONE),
#   - everyone with their teammates (TEAM),
#   - no one gets teleported at all (NONE),
playerTeleportStrategy: ALL

# If true, the game will send a message to players that died while playing the game
#   that can be used to teleport them back.
teleportBackAfterDeathMessage: true  # true or false

# The height (exact y-level) of the spawn platform at the start of the game
lobbySpawnHeight: 128

# Distances to teleport a player that uses the Go-Up-Wand
GoUpWand:
  upDistance: 75 # teleport up distance
  downDistance: 5 # teleport down distance, watch out for the void ;)
  cooldown: 5.0 # item cooldown in seconds
  platformLifetime: 10 # time in seconds that placed platforms will stay before disappearing.

# Decide what kit should be the default kit when loading the plugin:
#   - (HARDCORE)
#   - (NORMAL)
#   - (OVERPOWERED)
#   - (RELOADED)
defaultKit: OVERPOWERED

# The period of time (in seconds) at the start of the game when a player is protected from any damage
#   also determines the time after which the spawn platform will disappear.
gracePeriod: 30

# The card that the game will select automatically when starting the server/ reloading the plugin
selectedCard: default_card

# The yml file that contains the language data that will be used for this plugin
#   Choose from: en_us.yml, nl.yml, fr_fr.yml
language: en_us.yml

# Countdown time in minutes that is used for the Countdown gamemode.
countdownTime: 20

# Save player statistics (stats) like wins, losses, tasks completed, etc... Used for the leaderboard. Stats are saved to player_stats.yml.
#   Stats are not automatically removed if you turn this to false if it has been on true before.
#   Turning this option on later will not retroactively fill stats for games played with stats off.
savePlayerStatistics: false # true or false

